# Generated by Django 2.0.5 on 2018-05-27 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_hit', models.DateTimeField(auto_now_add=True)),
                ('last_hit', models.DateTimeField(auto_now=True)),
                ('req_headers', models.TextField(max_length=2048)),
                ('parsed_headers', models.TextField(blank=True, max_length=2048, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackingCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256, unique=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=256)),
                ('number_of_trackers', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='trackingcode',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iplogger.User'),
        ),
        migrations.AddField(
            model_name='log',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iplogger.TrackingCode'),
        ),
    ]
