# Generated by Django 2.0.5 on 2018-05-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplogger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingcode',
            name='code',
            field=models.IntegerField(max_length=256, unique=True),
        ),
    ]
