# Generated by Django 2.0.5 on 2018-05-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplogger', '0002_auto_20180527_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingcode',
            name='code',
            field=models.IntegerField(unique=True),
        ),
    ]
