# Generated by Django 2.0.5 on 2018-06-14 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iplogger', '0002_log_hit_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='req_headers',
            new_name='headers_info',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='parsed_headers',
            new_name='parsed_headers_info',
        ),
    ]
