# Generated by Django 2.1.5 on 2019-01-13 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iplogger', '0003_auto_20180614_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingcode',
            name='redirect_uri',
            field=models.URLField(default='https://www.google.com'),
        ),
        migrations.AlterField(
            model_name='trackingcode',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codes', to=settings.AUTH_USER_MODEL),
        ),
    ]
