# Generated by Django 2.0.5 on 2018-05-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplogger', '0003_auto_20180527_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingcode',
            name='code',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
