# Generated by Django 2.1.5 on 2019-01-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplogger', '0004_auto_20190113_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='internal_ip',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
