# Generated by Django 3.1.2 on 2020-10-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplogger', '0005_log_internal_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingcode',
            name='code',
            field=models.CharField(default='N/A', max_length=16),
        ),
    ]
